### ISSUE TITLE
Deletion of a tree immediately after opening the tree UI 'freezes' the UI

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#57]
Description: Deleting a tree in the sidebar of the tree editor UI immediately after opening it seems to prevent any more changes being made inside the window until you close and reopen the tree UI
Reproduction:
- Open the tree editor UI when there are already trees in the system
- Delete a tree from the sidebar
- Editing and creating nodes will now be impossible

**Comment by cev092** [comment]
When a tree is deleted shortly after the UI begins, the tree selection buttons become bugged and they begin referencing trees that they are not assigned to. Example: deleting tree 3 will have trees 1 and 2 working correctly, but all trees above 3 will reference the one below it. As a result tree 4 will not work, because folder 3 has been deleted, and the other trees will update the folder at tree #-1.

**Comment by willymcgeejr** [comment]
Resolved in Merge 44cb274 to develop
